services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  NullDev\Skeleton\Path\Readers\SourceCodePathReader: ~

  cli.command.nemesis.index:
    class: NullDev\Nemesis\Command\IndexCliCommand
    tags:
      - {name: console.command }

