services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  cli.command.nemesis.index:
    class: NullDev\Nemesis\Command\GeneratePHPUnitTestsCliCommand
    tags:
      - {name: console.command }

  