version: 2
jobs:
  build:
    docker:
      - image: msvrtan/square:0.2.1
    workDir: /var/www
    steps:
      - checkout
      - restore_cache:
          key: cache-v1-{{ checksum "composer.lock" }}
      - run:
          name: Composer install
          command: composer install --no-interaction
      - run: cp etc/circleci2/phpspec.yml phpspec.yml
      - run:
          name: PHPSpec
          command: ./vendor/bin/phpspec run --no-interaction
      - save_cache:
          key: cache-v1-{{ checksum "composer.lock" }}
          paths:
            - /var/www/vendor
      - type: artifacts-store
        path: build
        destination: build

  phpunit:
    docker:
      - image: msvrtan/square:0.2.1
    workDir: /var/www
    steps:
      - checkout
      - restore_cache:
          key: cache-v1-{{ checksum "composer.lock" }}
      - run:
          name: Composer install
          command: composer install --no-interaction
      - run:
          name: PHPUnit
          command: ./vendor/bin/phpunit --fail-on-warning --log-junit build/phpunit/junit.xml
      - type: artifacts-store
        path: build
        destination: build
      - store_test_results:
          path: build

  behat:
    docker:
      - image: msvrtan/square:0.2.1
    workDir: /var/www
    steps:
      - checkout
      - restore_cache:
          key: cache-v1-{{ checksum "composer.lock" }}
      - run:
          name: Composer install
          command: composer install --no-interaction
      - run:
          name: PHPUnit
          command: ./vendor/bin/behat
      - type: artifacts-store
        path: build
        destination: build
      - store_test_results:
          path: build

  codestyle:
    docker:
      - image: msvrtan/square:0.2.1
    workDir: /var/www
    steps:
      - checkout
      - restore_cache:
          key: cache-v1-{{ checksum "composer.lock" }}
      - run:
          name: Disable xdebug
          command: ./etc/circleci2/disable-xdebug.sh
      - run:
          name: Composer install
          command: composer install --no-interaction
      - run:
          name: Check codestandards
          command: ./vendor/bin/phing check-codestandards

  phpstan:
    docker:
      - image: msvrtan/square:0.2.1
    workDir: /var/www
    steps:
      - checkout
      - restore_cache:
          key: cache-v1-{{ checksum "composer.lock" }}
      - run:
          name: Disable xdebug
          command: ./etc/circleci2/disable-xdebug.sh
      - run:
          name: Composer install
          command: composer install --no-interaction
      - run:
          name: Static analysis
          command: ./vendor/bin/phing phpstan

  humbug:
    docker:
      - image: msvrtan/square:0.2.1
    workDir: /var/www
    steps:
      - checkout
      - restore_cache:
          key: cache-v1-{{ checksum "composer.lock" }}
      - run:
          name: Humbug
          command: ./vendor/bin/humbug
      - store_artifacts:
          path: build
          destination: build

  highest:
    docker:
      - image: msvrtan/square:0.2.1
    workDir: /var/www
    steps:
      - checkout
      - restore_cache:
          key: cache-v1-{{ checksum "composer.lock" }}
      - run:
          name: Disable xdebug
          command: ./etc/circleci2/disable-xdebug.sh
      - run:
          name: Delete composer.lock
          command: rm composer.lock
      - run:
          name: Composer install
          command: composer install --no-interaction
      - run:
          name: PHPUnit
          command: ./vendor/bin/phpunit
      - run:
          name: PHPSpec
          command: ./vendor/bin/phpspec run --no-interaction
      - run:
          name: Check codestandards
          command: ./vendor/bin/phing check-codestandards
      - run:
          name: Static analysis
          command: ./vendor/bin/phing phpstan

  phar:
    docker:
      - image: msvrtan/square:0.2.1
    workDir: /var/www
    steps:
      - checkout
      - restore_cache:
          key: cache-v1-{{ checksum "composer.lock" }}
      - run:
          name: Composer install
          command: composer install --no-interaction --no-dev
      - run:
          name: Build Phar
          command: php -d phar.readonly=false box.phar build -v

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
         filters:
           branches:
             ignore: building-phar
      - phpunit:
         filters:
           branches:
             ignore: building-phar
      - behat:
         filters:
           branches:
             ignore: building-phar
      - codestyle:
         filters:
           branches:
             ignore: building-phar
      - phpstan:
         filters:
           branches:
             ignore: building-phar
      - phar:
         filters:
           branches:
             only: building-phar
      - humbug:
         requires:
           - phpunit
      - highest:
         requires:
           - build
         filters:
           branches:
             only: master
