parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  NullDevelopment\SkeletonBroadwayExtension\Command\SourceCode\CommandLoader: ~
  NullDevelopment\SkeletonBroadwayExtension\Event\SourceCode\EventLoader: ~
  NullDevelopment\SkeletonBroadwayExtension\EventSourcedEntity\SourceCode\EventSourcedEntityLoader: ~
  NullDevelopment\SkeletonBroadwayExtension\EventSourcedAggregateRoot\SourceCode\EventSourcedAggregateRootLoader: ~
  NullDevelopment\SkeletonBroadwayExtension\EventSourcingRepository\SourceCode\EventSourcingRepositoryLoader: ~
  NullDevelopment\SkeletonBroadwayExtension\CommandHandler\SourceCode\CommandHandlerLoader: ~
  NullDevelopment\SkeletonBroadwayExtension\DoctrineRead\SourceCode\DoctrineReadEntityLoader: ~
  NullDevelopment\SkeletonBroadwayExtension\DoctrineRead\SourceCode\DoctrineReadRepositoryLoader: ~
  NullDevelopment\SkeletonBroadwayExtension\DoctrineRead\SourceCode\DoctrineReadProjectorLoader: ~
  NullDevelopment\SkeletonBroadwayExtension\DoctrineRead\SourceCode\DoctrineReadFactoryLoader: ~


  NullDevelopment\SkeletonBroadwayExtension\Event\SourceCodeGenerator\Method\CreateEventMethodGenerator: ~
  NullDevelopment\SkeletonBroadwayExtension\Event\PhpSpecGenerator\Method\SpecCreateEventMethodGenerator: ~
  NullDevelopment\SkeletonBroadwayExtension\Event\PhpUnitGenerator\Method\TestCreateEventMethodGenerator: ~

  NullDevelopment\SkeletonBroadwayExtension\CommandHandler\SourceCodeGenerator\Method\LoadMethodGenerator: ~
  NullDevelopment\SkeletonBroadwayExtension\CommandHandler\SourceCodeGenerator\Method\SaveMethodGenerator: ~

  NullDevelopment\SkeletonBroadwayExtension\DoctrineRead\SourceCodeGenerator\Method\SaveMethodGenerator: ~
  NullDevelopment\SkeletonBroadwayExtension\DoctrineRead\SourceCodeGenerator\Method\RemoveMethodGenerator: ~

