parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  NullDevelopment\SkeletonBroadwayExtension\Command\SourceCode\CommandLoader: ~
  NullDevelopment\SkeletonBroadwayExtension\Event\SourceCode\EventLoader: ~
  NullDevelopment\SkeletonBroadwayExtension\EventSourcedEntity\SourceCode\EventSourcedEntityLoader: ~
  NullDevelopment\SkeletonBroadwayExtension\EventSourcedAggregateRoot\SourceCode\EventSourcedAggregateRootLoader: ~
  NullDevelopment\SkeletonBroadwayExtension\EventSourcingRepository\SourceCode\EventSourcingRepositoryLoader: ~


