parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  NullDevelopment\SkeletonBroadwayExtension\Command\SourceCode\CommandLoader: ~
  NullDevelopment\SkeletonBroadwayExtension\Event\SourceCode\EventLoader: ~
