services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true


  NullDev\Nemesis\Config\ConfigFactory: ~

  NullDev\Nemesis\Config\Config:
    class: NullDev\Nemesis\Config\Config
    factory: ['@NullDev\Nemesis\Config\ConfigFactory', create]


  NullDev\Nemesis\SourceParser\PhpParserSourceParser: ~
  NullDev\Nemesis\SourceParser\ReflectionSourceParser: ~

  Symfony\Component\Filesystem\Filesystem: ~