services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

#  NullDevelopment\SkeletonNetteGenerator\SourceCode\Generator\SimpleValueObjectNetteGenerator:
#    tags:
#      - { name: skeleton.source_code_generator }
#  NullDevelopment\SkeletonNetteGenerator\SourceCode\Generator\SimpleCollectionNetteGenerator:
#    tags:
#      - { name: skeleton.source_code_generator }
#  NullDevelopment\SkeletonNetteGenerator\SourceCode\Generator\DateTimeValueObjectNetteGenerator:
#    tags:
#      - { name: skeleton.source_code_generator }
#  NullDevelopment\SkeletonNetteGenerator\SourceCode\Generator\SimpleEntityNetteGenerator:
#    tags:
#      - { name: skeleton.source_code_generator }
#  NullDevelopment\SkeletonNetteGenerator\SourceCode\Generator\SimpleIdentifierNetteGenerator:
#    tags:
#      - { name: skeleton.source_code_generator }


  NullDevelopment\SkeletonNetteGenerator\PhpSpec\Generator\SimpleValueObjectSpecNetteGenerator:
    tags:
      - { name: skeleton.php_spec_generator }
  NullDevelopment\SkeletonNetteGenerator\PhpSpec\Generator\SimpleCollectionSpecNetteGenerator:
    tags:
      - { name: skeleton.php_spec_generator }
  NullDevelopment\SkeletonNetteGenerator\PhpSpec\Generator\DateTimeValueObjectSpecNetteGenerator:
    tags:
      - { name: skeleton.php_spec_generator }
  NullDevelopment\SkeletonNetteGenerator\PhpSpec\Generator\SimpleEntitySpecNetteGenerator:
    tags:
      - { name: skeleton.php_spec_generator }
  NullDevelopment\SkeletonNetteGenerator\PhpSpec\Generator\SimpleIdentifierSpecNetteGenerator:
    tags:
      - { name: skeleton.php_spec_generator }



  NullDevelopment\SkeletonNetteGenerator\PhpUnit\Generator\SimpleValueObjectTestNetteGenerator:
    tags:
      - { name: skeleton.php_unit_generator }
  NullDevelopment\SkeletonNetteGenerator\PhpUnit\Generator\SimpleCollectionTestNetteGenerator:
    tags:
      - { name: skeleton.php_unit_generator }
  NullDevelopment\SkeletonNetteGenerator\PhpUnit\Generator\DateTimeValueObjectTestNetteGenerator:
    tags:
      - { name: skeleton.php_unit_generator }
  NullDevelopment\SkeletonNetteGenerator\PhpUnit\Generator\SimpleEntityTestNetteGenerator:
    tags:
      - { name: skeleton.php_unit_generator }
  NullDevelopment\SkeletonNetteGenerator\PhpUnit\Generator\SimpleIdentifierTestNetteGenerator:
    tags:
      - { name: skeleton.php_unit_generator }


  NullDevelopment\SkeletonNetteGenerator\SourceCode\Generator\DateTimeValueObjectNetteGenerator:
    tags:
      - { name: tactician.handler, command: 'NullDevelopment\Skeleton\Definition\DateTimeValueObject' }

  NullDevelopment\SkeletonNetteGenerator\SourceCode\Generator\SimpleEntityNetteGenerator:
    tags:
      - { name: tactician.handler, command: 'NullDevelopment\Skeleton\Definition\SimpleEntity' }

  NullDevelopment\SkeletonNetteGenerator\SourceCode\Generator\SimpleIdentifierNetteGenerator:
    tags:
      - { name: tactician.handler, command: 'NullDevelopment\Skeleton\Definition\SimpleIdentifier' }

  NullDevelopment\SkeletonNetteGenerator\SourceCode\Generator\SimpleValueObjectNetteGenerator:
    tags:
      - { name: tactician.handler, command: 'NullDevelopment\Skeleton\Definition\SimpleValueObject' }

  NullDevelopment\SkeletonNetteGenerator\SourceCode\Generator\SimpleCollectionNetteGenerator:
    tags:
      - { name: tactician.handler, command: 'NullDevelopment\Skeleton\Definition\SimpleCollection' }

  NullDevelopment\SkeletonNetteGenerator\SourceCode\Generator\SimpleTraitNetteGenerator:
    tags:
      - { name: tactician.handler, command: 'NullDevelopment\PhpStructure\Type\TraitDefinition' }

  NullDevelopment\SkeletonNetteGenerator\SourceCode\Generator\SimpleInterfaceNetteGenerator:
    tags:
      - { name: tactician.handler, command: 'NullDevelopment\PhpStructure\Type\InterfaceDefinition' }


  NullDevelopment\SkeletonNetteGenerator\PhpUnit\PHPUnitTestMiddleware:
    tags:
      - { name: tactician.middleware , priority: 50 }

  NullDevelopment\SkeletonNetteGenerator\PhpSpec\PHPSpecMiddleware:
    tags:
      - { name: tactician.middleware , priority: 50 }
