services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true


  NullDev\BroadwaySkeleton\Handler\BroadwayAggregateRootIdHandler:
    tags:
      - { name: tactician.handler, command: 'NullDev\BroadwaySkeleton\Command\CreateBroadwayAggregateRootId' }
  NullDev\BroadwaySkeleton\Handler\BroadwayAggregateRootModelHandler:
    tags:
      - { name: tactician.handler, command: 'NullDev\BroadwaySkeleton\Command\CreateBroadwayAggregateRootModel' }
  NullDev\BroadwaySkeleton\Handler\BroadwayAggregateRootRepositoryHandler:
    tags:
      - { name: tactician.handler, command: 'NullDev\BroadwaySkeleton\Command\CreateBroadwayAggregateRootRepository' }
  NullDev\BroadwaySkeleton\Handler\BroadwayCommandHandler:
    tags:
      - { name: tactician.handler, command: 'NullDev\BroadwaySkeleton\Command\CreateBroadwayCommand' }

  NullDev\BroadwaySkeleton\Handler\BroadwayEventHandler:
    tags:
      - { name: tactician.handler, command: 'NullDev\BroadwaySkeleton\Command\CreateBroadwayEvent' }
  NullDev\BroadwaySkeleton\Handler\BroadwayCommandHandlerHandler:
    tags:
      - { name: tactician.handler, command: 'NullDev\BroadwaySkeleton\Command\CreateBroadwayCommandHandler' }


  NullDev\BroadwaySkeleton\Handler\BroadwayDoctrineOrmReadEntityHandler:
    tags:
      - { name: tactician.handler, command: 'NullDev\BroadwaySkeleton\Command\CreateBroadwayDoctrineOrmReadEntity' }
  NullDev\BroadwaySkeleton\Handler\BroadwayDoctrineOrmReadRepositoryHandler:
    tags:
      - { name: tactician.handler, command: 'NullDev\BroadwaySkeleton\Command\CreateBroadwayDoctrineOrmReadRepository' }
  NullDev\BroadwaySkeleton\Handler\BroadwayDoctrineOrmReadFactoryHandler:
    tags:
      - { name: tactician.handler, command: 'NullDev\BroadwaySkeleton\Command\CreateBroadwayDoctrineOrmReadFactory' }
  NullDev\BroadwaySkeleton\Handler\BroadwayDoctrineOrmReadProjectorHandler:
    tags:
      - { name: tactician.handler, command: 'NullDev\BroadwaySkeleton\Command\CreateBroadwayDoctrineOrmReadProjector' }

  NullDev\BroadwaySkeleton\Handler\BroadwayElasticsearchReadEntityHandler:
    tags:
      - { name: tactician.handler, command: 'NullDev\BroadwaySkeleton\Command\CreateBroadwayElasticsearchReadEntity' }
  NullDev\BroadwaySkeleton\Handler\BroadwayElasticsearchReadRepositoryHandler:
    tags:
      - { name: tactician.handler, command: 'NullDev\BroadwaySkeleton\Command\CreateBroadwayElasticsearchReadRepository' }
  NullDev\BroadwaySkeleton\Handler\BroadwayElasticsearchReadProjectorHandler:
    tags:
      - { name: tactician.handler, command: 'NullDev\BroadwaySkeleton\Command\CreateBroadwayElasticsearchReadProjector' }


  NullDev\BroadwaySkeleton\CodeGenerator\PhpParser\Methods\CommandHandler\LoadAggregateRootModelGenerator: ~
  NullDev\BroadwaySkeleton\CodeGenerator\PhpParser\Methods\CommandHandler\SaveAggregateRootModelGenerator: ~
  NullDev\BroadwaySkeleton\CodeGenerator\PhpParser\Methods\DeserializeGenerator: ~
  NullDev\BroadwaySkeleton\CodeGenerator\PhpParser\Methods\SerializeGenerator: ~
  NullDev\BroadwaySkeleton\CodeGenerator\PhpParser\Methods\Model\AggregateRootIdGetterGenerator: ~
  NullDev\BroadwaySkeleton\CodeGenerator\PhpParser\Methods\Model\CreateGenerator: ~
  NullDev\BroadwaySkeleton\CodeGenerator\PhpParser\Methods\Model\ReadModelIdGetterGenerator: ~
  NullDev\BroadwaySkeleton\CodeGenerator\PhpParser\Methods\Model\RepositoryConstructorGenerator: ~
  NullDev\BroadwaySkeleton\SourceFactory\CommandSourceFactory: ~
  NullDev\BroadwaySkeleton\SourceFactory\EventSourcedAggregateRootSourceFactory: ~
  NullDev\BroadwaySkeleton\SourceFactory\EventSourceFactory: ~
  NullDev\BroadwaySkeleton\SourceFactory\EventSourcingRepositorySourceFactory: ~
  NullDev\BroadwaySkeleton\SourceFactory\Read\DoctrineOrm\ReadEntitySourceFactory: ~
  NullDev\BroadwaySkeleton\SourceFactory\Read\DoctrineOrm\ReadFactorySourceFactory: ~
  NullDev\BroadwaySkeleton\SourceFactory\Read\DoctrineOrm\ReadProjectorSourceFactory: ~
  NullDev\BroadwaySkeleton\SourceFactory\Read\DoctrineOrm\ReadRepositorySourceFactory: ~
  NullDev\BroadwaySkeleton\SourceFactory\Read\ElasticSearch\ReadEntitySourceFactory: ~
  NullDev\BroadwaySkeleton\SourceFactory\Read\ElasticSearch\ReadProjectorSourceFactory: ~
  NullDev\BroadwaySkeleton\SourceFactory\Read\ElasticSearch\ReadRepositorySourceFactory: ~