parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true



  NullDevelopment\SkeletonPhpUnitExtension\MethodGenerator\SetUpMethodGenerator: ~
  NullDevelopment\SkeletonPhpUnitExtension\MethodGenerator\TestGetterMethodGenerator: ~
  NullDevelopment\SkeletonPhpUnitExtension\MethodGenerator\TestHasPropertyMethodGenerator: ~
  NullDevelopment\SkeletonPhpUnitExtension\MethodGenerator\TestToStringMethodGenerator: ~
  NullDevelopment\SkeletonPhpUnitExtension\MethodGenerator\TestSerializeMethodGenerator: ~
  NullDevelopment\SkeletonPhpUnitExtension\MethodGenerator\TestDeserializeMethodGenerator: ~

  NullDevelopment\SkeletonPhpUnitExtension\MethodGenerator\TestDateTimeSetUpMethodGenerator: ~
  NullDevelopment\SkeletonPhpUnitExtension\MethodGenerator\TestDateTimeToStringMethodGenerator: ~
  NullDevelopment\SkeletonPhpUnitExtension\MethodGenerator\TestDateTimeCreateFromFormatMethodGenerator: ~
  NullDevelopment\SkeletonPhpUnitExtension\MethodGenerator\TestDateTimeSerializeMethodGenerator: ~
  NullDevelopment\SkeletonPhpUnitExtension\MethodGenerator\TestDateTimeDeserializeMethodGenerator: ~



  NullDevelopment\SkeletonPhpUnitExtension\MethodFactory\SetUpMethodFactory: ~
  NullDevelopment\SkeletonPhpUnitExtension\MethodFactory\TestGetterMethodFactory: ~
  NullDevelopment\SkeletonPhpUnitExtension\MethodFactory\TestHasPropertyMethodFactory: ~
  NullDevelopment\SkeletonPhpUnitExtension\MethodFactory\TestToStringMethodFactory: ~
  NullDevelopment\SkeletonPhpUnitExtension\MethodFactory\TestSerializeMethodFactory: ~
  NullDevelopment\SkeletonPhpUnitExtension\MethodFactory\TestDeserializeMethodFactory: ~

  NullDevelopment\SkeletonPhpUnitExtension\MethodFactory\TestDateTimeSetUpMethodFactory: ~
  NullDevelopment\SkeletonPhpUnitExtension\MethodFactory\TestDateTimeToStringMethodFactory: ~
  NullDevelopment\SkeletonPhpUnitExtension\MethodFactory\TestDateTimeCreateFromFormatMethodFactory: ~
  NullDevelopment\SkeletonPhpUnitExtension\MethodFactory\TestDateTimeSerializeMethodFactory: ~
  NullDevelopment\SkeletonPhpUnitExtension\MethodFactory\TestDateTimeDeserializeMethodFactory: ~




